Fix camelcasing inconsistency causing an assertion error.
java.lang.AssertionError: Searching for a field that's not there: serviceName
	at com.cloud.utils.db.SearchBase.set(SearchBase.java:219)
	at com.cloud.utils.db.SearchBase$Interceptor.intercept(SearchBase.java:475)
	at com.cloud.network.dao.MonitoringServiceVO$$EnhancerByCGLIB$$84195222.getServiceName(<generated>)
	at com.cloud.network.dao.MonitoringServiceDaoImpl.<init>(MonitoringServiceDaoImpl.java:41)