Set length for parameters that expect a list of domain ids. (#5763)
Currently, when updating a service offering there is a limitation of the number of domains the offering can be updated.

Multiple domain ids lead to the following API error:
Error: (HTTP 431, error code 9999) Unable to execute API command updateserviceoffering due to invalid value. Value greater than max allowed length 255 for param: domainIds"