CLOUDSTACK-5647 Adding F5 device to network service provider fails with NoClassDefFoundError
adding back missing (removed from 4.3) dependency 'commons-discovery'